markdown: rdiscount
pygments: true
permalink: /:year/:month/:day/:title.html
name: "yeah, the stuff"
markdown: rdiscount
production_url: http://liutaihua.github.io

author: "liutaihua"
atom-baseurl: "http://liutaihua.github.io"
disqus: "gopherwood"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Gallery
    class: fa fa-film
    href: http://www.flickr.com/photos/liutaihua/
  - title: Blogroll
    class: fa fa-link
    href: /links.html
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml

